In [23]:
"""Startup"""
%matplotlib inline
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tkinter import Variable
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn import preprocessing
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.naive_bayes import MultinomialNB
import time


pathToDataCollectorDatabase = 'D:\\PythonTestSmall'

In [3]:
def searchFiles(path, fileformats):
    filesToDo = []
    for root, dirs, files in os.walk(path):
        for file in files:
            for fileformat in fileformats:
                if file.endswith(fileformat):
                    #code to generate a list of paths of files to generate logs for
                    filesToDo.append(os.path.join(root, file).removeprefix(path))
    return filesToDo

def searchFileName(path, fileName):
    filesToDo = []
    for root, dirs, files in os.walk(path):
        for file in files:
            if file == fileName:
                #code to generate a list of paths of files to generate logs for
                filesToDo.append(os.path.join(root, file).removeprefix(path))
    return filesToDo

In [4]:

filesToIndex = searchFileName(pathToDataCollectorDatabase,"gitinfo.txt")
#Create a dataframe that contains the data of the gitinfo.txt files
import json
import warnings
warnings.filterwarnings('ignore')
i=0
#example of the gitinfo.txt file    {"id": 3452233, "name": "hjlebbink/asm-dude", "isFork": false, "commits": 939, "branches": 8, "defaultBranch": "master", "releases": 39, "contributors": 10, "license": "MIT License", "watchers": 762, "stargazers": 3906, "forks": 76, "size": 82262, "createdAt": "2016-02-19 03:43:23", "pushedAt": "2022-01-06 01:33:34", "updatedAt": "2022-01-08 08:02:49", "homepage": "", "mainLanguage": "Python", "totalIssues": 118, "openIssues": 32, "totalPullRequests": 13, "openPullRequests": 1, "lastCommit": "2021-12-07 08:47:07", "lastCommitSHA": "1e1e3dc2364e8ed549ba404868b6473ba435b25c", "hasWiki": true, "isArchived": false, "languages": {"Python": 4274689, "C#": 2554588, "C": 1311140, "C++": 644077, "Assembly": 164163, "Shell": 2764, "Go": 1779, "Batchfile": 410}, "labels": ["bug", "duplicate", "enhancement", "help wanted", "invalid", "question", "wontfix"]}
df = pd.DataFrame(columns=['id', 'name', 'isFork', 'commits', 'branches', 'defaultBranch', 'releases', 'contributors', 'license', 'watchers', 'stargazers', 'forks', 'size', 'createdAt', 'pushedAt', 'updatedAt', 'homepage', 'mainLanguage', 'totalIssues', 'openIssues', 'totalPullRequests', 'openPullRequests', 'lastCommit', 'lastCommitSHA', 'hasWiki', 'isArchived', 'languages', 'labels' , 'path'])
for file in filesToIndex:
    with open(pathToDataCollectorDatabase + file, 'r') as f:
        d = json.load(f)
    f.close()
    dftemp = pd.json_normalize(d)
    dftemp['path'] = file.removesuffix('gitinfo.txt')
    df = pd.concat([df, dftemp], ignore_index=True)
    i = i+1
df


id                                   name isFork commits branches  \
0   3468763            albumidentify/albumidentify  False     758        6   
1   3452233                     hjlebbink/asm-dude  False     939        8   
2   3466103                            sebnow/aur2  False     174        7   
3   3466989                         dasich/brownie  False     503        6   
4   3470338                             ask/carrot  False     499       17   
5   3466377              bmbouter/celerymanagement  False     569        5   
6   3466979                            ask/chishop  False     159        6   
7   3467538                adamklawonn/citycircles  False     421        6   
8   3469579                   okfn/ckanext-example  False      55        5   
9   3275794          googlecloudplatform/community  False    1430        9   
10  3468166          4zm/dandelion-message-service  False     184        5   
11  3471736            stephrdev/django-mongoforms  False      44        5   
12  3471715            django-nonrel/django-nonrel  False   20532        6   
13  3471019    jtauber-archive/django-notification  False     163        5   
14  3277687                        feast-dev/feast  False    2636       30   
15  3468973                   gmcquillan/firetower  False     225       13   
16  3468644                 wilsaj/flask-admin-old  False     469       12   
17  3470977                            eevee/floof  False     495       11   
18  3471020                        progrium/ginkgo  False     263        5   
19  3467640                    bmander/graphserver  False     932       17   
20  3458022                 lightstep/hipster-shop  False     641       39   
21  3468717                global-pulse/hunchworks  False     831       21   
22  3470003                    ilastik/ilastik-0.5  False    1760       12   
23  3467930                   flaptor/indextank-py  False      50        7   
24  3469397                      keokilee/makahiki  False    2549        9   
25  3468649        codeforamerica/open311dashboard  False     278       11   
26  3465634                         ctb/pony-build  False     426       12   
27  3470358                        disqus/porkchop  False     148        5   
28  2444449  coursera/programming-assignments-demo  False     124       21   
29  3470353                  futurecore/python-csp  False     353        8   
30  3467644             simplegeo/python-simplegeo  False     228        7   
31  3467114             typepad/python-typepad-api  False     704        9   
32  3470316                      qualitio/qualitio  False    1292       10   
33  3470630                                jni/ray  False     755       12   
34  3467146                       fwenzel/reporter  False    1392        6   
35  3275944             returntocorp/semgrep-rules  False    2234      171   
36  3467326                        rcoh/smootlight  False     601       41   
37  3471002               morgancabral/sse-library  False     100        5   
38  3468754                   vereseproject/verese  False     205        5   
39  3275868         zettelkasten-team/zettelkasten  False     948       14   

   defaultBranch releases contributors                              license  \
0         master        0            6                                 None   
1         master       39           10                          MIT License   
2         master        0            5                                 None   
3         master        0            5                                Other   
4         master       19           14  BSD 3-Clause New or Revised License   
5         master        4            5                                 None   
6         master        2           12  BSD 3-Clause New or Revised License   
7         master        0            7      GNU General Public License v3.0   
8         master        1            6                                 None   
9         master    

In [8]:
#EXPERIMENT 1: Grade Generation Based off of the number of commits
#Formula: round((commit/totalCommits)*100)
#This is a very simple formula that will be used to generate a grade for the number of commits as the first dataset used to train the model
#read the file path from the dataframe
filesToIndex = df['path'].tolist()
#Create an array of strings of folders which contain a 0.txt file
foldersWithCommits = []
for file in filesToIndex:
    for filelvl2 in searchFileName(pathToDataCollectorDatabase+file, "0.txt"):
        foldersWithCommits.append(file+filelvl2.removesuffix('0.txt'))

#get the total number of commits for each folder
totalCommits = []
for folder in foldersWithCommits:
    totalCommits.append(len(searchFiles(pathToDataCollectorDatabase+folder, ['.txt'])))

dataSet1 = pd.DataFrame(columns=['data', 'grade'])
for i in foldersWithCommits:
    #get the number of commits for each folder
    numberOfCommits = len(searchFiles(pathToDataCollectorDatabase+i, ['.txt']))
    for j in range(len(searchFiles(pathToDataCollectorDatabase+i, ['.txt']))):
        skip = False
        #open 'j'.txt and read it
        data = open(pathToDataCollectorDatabase+i+str(j)+'.txt', 'r', encoding="utf8")
        dataread = data.read()
        #add the data to the dataframe
        if (numberOfCommits > 3):
            dataSet1temp = pd.DataFrame({'data': dataread, 'grade': round((j/numberOfCommits)*100)}, index=[0])
        elif (numberOfCommits <= 1):
            skip = True
        else:
            #add a grade starting from 50% if there are less than 3 commits
            dataSet1temp = pd.DataFrame({'data': dataread, 'grade': round(((j/numberOfCommits)*100)*.5+50)}, index=[0])
        if (skip == False):
            dataSet1 = pd.concat([dataSet1, dataSet1temp], ignore_index=True)
        #close the file
        data.close()
dataSet1


data grade
0      #!/usr/bin/python\nimport os\nimport lookups\n...     0
1      #!/usr/bin/python\nimport os\nimport lookups\n...    25
2      #!/usr/bin/python\nimport os\nimport lookups\n...    50
3      #!/usr/bin/python\nimport os\nimport lookups\n...    75
4      import ConfigParser\nimport os\n\nconfig=Confi...     0
...                                                  ...   ...
17284  #!/usr/bin/env python\n"""\nUsage: update_site...    62
17285  #!/usr/bin/env python\n"""\nUsage: update_site...    75
17286  #!/usr/bin/env python\n"""\nUsage: update_site...    88
17287  #!/usr/bin/python3\n\nimport os\n\nrootdir = r...    50
17288  import os\n\nrootdir = r'/Users/rgb/Projects/Z...    75

[17289 rows x 2 columns]

In [9]:
#Dataset Structure (Data, Grade Value)
#Grade Value: 0 = Bad, 100 = Good (int)
#Data: (String)

#Create a dataset 

#print(dataSet1['grade'].value_counts())

#use the regex  \".*?\" to remove the text between quotes
dataSet1['data'] = dataSet1['data'].str.replace(r'\".*?\"', "\"stringGoesHere\"", regex=True)
#use the regex  \'.*?\' to remove the text between quotes
dataSet1['data'] = dataSet1['data'].str.replace(r'\'.*?\'', '\"stringGoesHere\"', regex=True)
dataSet1

data grade
0      #!/usr/bin/python\nimport os\nimport lookups\n...     0
1      #!/usr/bin/python\nimport os\nimport lookups\n...    25
2      #!/usr/bin/python\nimport os\nimport lookups\n...    50
3      #!/usr/bin/python\nimport os\nimport lookups\n...    75
4      import ConfigParser\nimport os\n\nconfig=Confi...     0
...                                                  ...   ...
17284  #!/usr/bin/env python\n"stringGoesHere""\nUsag...    62
17285  #!/usr/bin/env python\n"stringGoesHere""\nUsag...    75
17286  #!/usr/bin/env python\n"stringGoesHere""\nUsag...    88
17287  #!/usr/bin/python3\n\nimport os\n\nrootdir = r...    50
17288  import os\n\nrootdir = r"stringGoesHere"\n\nfo...    75

[17289 rows x 2 columns]

In [24]:
#make the ML methods into diffrent classes so that they can be used in diffrent threads
def naiveBayes(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #Naive Bayes
    from sklearn.naive_bayes import MultinomialNB
    naive = MultinomialNB().fit(xtrain, ytrain)
    ypred = naive.predict(xtest)
    print("Naive Bayes Accuracy: ", naive.score(xtest,ytest))
    print("Naive Bayes\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time: ", end-start)

def logisticRegression(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #Logistic Regression
    from sklearn.linear_model import LogisticRegression
    logistic = LogisticRegression().fit(xtrain, ytrain)
    ypred = logistic.predict(xtest)
    print("Logistic Regression Accuracy: ", logistic.score(xtest,ytest))
    print("Logistic Regression\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time: ", end-start)

def randomForest(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #Random Forest
    from sklearn.ensemble import RandomForestClassifier
    randomForest = RandomForestClassifier().fit(xtrain, ytrain)
    ypred = randomForest.predict(xtest)
    print("Random Forest Accuracy: ", randomForest.score(xtest,ytest))
    print("Random Forest\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time: ", end-start)

def supportVectorMachine(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #Support Vector Machine
    from sklearn.svm import SVC
    supportVectorMachine = SVC().fit(xtrain, ytrain)
    ypred = supportVectorMachine.predict(xtest)
    print("Support Vector Machine Accuracy: ", supportVectorMachine.score(xtest,ytest))
    print("Support Vector Machine\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time: ", end-start)

def kNearestNeighbors(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #K Nearest Neighbors
    from sklearn.neighbors import KNeighborsClassifier
    kNearestNeighbors = KNeighborsClassifier().fit(xtrain, ytrain)
    ypred = kNearestNeighbors.predict(xtest)
    print("K Nearest Neighbors Accuracy: ", kNearestNeighbors.score(xtest,ytest))
    print("K Nearest Neighbors\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time: ", end - start)

def decisionTree(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #Decision Tree
    from sklearn.tree import DecisionTreeClassifier
    decisionTree = DecisionTreeClassifier().fit(xtrain, ytrain)
    ypred = decisionTree.predict(xtest)
    print("Decision Tree Accuracy: ", decisionTree.score(xtest,ytest))
    print("Decision Tree\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time: ", end - start)

def gradientBoosting(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #Gradient Boosting
    from sklearn.ensemble import GradientBoostingClassifier
    gradientBoosting = GradientBoostingClassifier().fit(xtrain, ytrain)
    ypred = gradientBoosting.predict(xtest)
    print("Gradient Boosting Accuracy: ", gradientBoosting.score(xtest,ytest))
    print("Gradient Boosting\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time taken: ", end-start)

def neuralNetwork(xtrain,ytrain,xtest,ytest):
    start = time.time()
    #Neural Network
    from sklearn.neural_network import MLPClassifier
    neuralNetwork = MLPClassifier().fit(xtrain, ytrain)
    ypred = neuralNetwork.predict(xtest)
    print("Neural Network Accuracy: ", neuralNetwork.score(xtest,ytest))
    print("Neural Network\n")
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred, average='weighted'))
    print("Precision: ", precision_score(y_test, y_pred, average='weighted'))
    print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))
    print("Classification Report: ", classification_report(y_test, y_pred))
    print("\n")
    end = time.time()
    print("Time: ", end - start)



In [19]:
"Feature Creation"
"For data that only has a data column and a target column as 0 and 1 respectively using a pandas dataframe"
def featureCreationPython(dataSet):
    countVectorizer = CountVectorizer(lowercase=True, min_df=0.01, max_df=0.95, ngram_range=(1, 4), token_pattern=r'(?u)\b\w\w+\b|\t|[^\s]')
    X = countVectorizer.fit_transform(dataSet[dataSet.columns[0]].values , dataSet[dataSet.columns[1]].values)
    tfidfTransformer = TfidfTransformer()
    X = tfidfTransformer.fit_transform(X)
    return X

In [22]:

from tkinter import Variable
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn import preprocessing
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.naive_bayes import MultinomialNB



#impliment a better regex tokenizer for programing languages
#tokenizer regex value = r'(?u)\b\w\w+\b|\t|[^\s]'
X = featureCreationPython(dataSet1)
X_train, X_test, y_train, y_test = train_test_split(X, dataSet1['grade'].to_list(), test_size=0.2, random_state=42)




NameError: name 'time' is not defined

In [25]:
multithread = True

if (multithread):
    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=8) as executor:
        executor.submit(logisticRegression, X_train, y_train, X_test, y_test)
        executor.submit(supportVectorMachine, X_train, y_train, X_test, y_test)
        executor.submit(kNearestNeighbors, X_train, y_train, X_test, y_test)
        executor.submit(decisionTree, X_train, y_train, X_test, y_test)
        executor.submit(gradientBoosting, X_train, y_train, X_test, y_test)
        executor.submit(neuralNetwork, X_train, y_train, X_test, y_test)
else:
    logisticRegression(X_train, y_train, X_test, y_test)
    supportVectorMachine(X_train, y_train, X_test, y_test)
    kNearestNeighbors(X_train, y_train, X_test, y_test)
    decisionTree(X_train, y_train, X_test, y_test)
    gradientBoosting(X_train, y_train, X_test, y_test)
    neuralNetwork(X_train, y_train, X_test, y_test)

K Nearest Neighbors Accuracy:  0.021110468478889532
K Nearest Neighbors

Accuracy:  0.06824754193175246
F1 Score:  0.014551588378705394
Precision:  0.008275408984813814
Confusion Matrix:  [[48  0  0 ...  0  0  0]
 [ 6  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 5  0  0 ...  0  0  0]
 [ 3  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
Classification Report:                precision    recall  f1-score   support

           0       0.05      0.22      0.08       218
           1       0.00      0.00      0.00         9
           2       0.00      0.00      0.00        10
           3       0.00      0.00      0.00        25
           4       0.00      0.00      0.00        23
           5       0.00      0.00      0.00        26
           6       0.00      0.00      0.00        23
           7       0.00      0.00      0.00        29
           8       0.00      0.00      0.00        38
           9       0.00      0.00      0.00        28
          10       0.00      0.00    

In [49]:
#open a file and store the data in a variable
data = open("C:\\Users\\Mcall\\Desktop\\test.py", 'r', encoding="utf8")
datareaded = data.read()
#close the file
data.close()

#write a value to docs_new to test the model with python code that has 3 comments and a for loop with 3 iterations
docs_new = [datareaded]
X_new_counts = countVectorizer.transform(docs_new)
X_new_tfidf = tf_transformer.transform(X_new_counts)
print(X_new_tfidf)
print(X_new_tfidf.shape)
predicted = clf.predict(X_new_tfidf)

for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, category))


ValueError: X has 54785 features, but TfidfTransformer is expecting 266758 features as input.